[window]
dimensions = { columns = 140, lines = 40 }
opacity = 0.85

[scrolling]
history = 25000

[colors.primary]
foreground = "#ffffff"
background = "#000000"

[font]
size = 13.0

[font.bold]
family = "monospace"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "monospace"
style = "Regular"
