[window]
dimensions = { columns = 140, lines = 40 }
opacity = 0.95

[scrolling]
history = 25000

[colors.primary]
foreground = "#fafafa"
background = "#151515"

[font]
size = 12.0

[font.bold]
family = "monospace"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "monospace"
style = "Regular"
